# conda.yaml
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch==2.5.1  # pytorch 채널에서 명시적으로 가져옴
  - pytorch::torchvision==0.20.1 # torch 2.5.1과 호환되는 버전
  - pytorch::pytorch-cuda=12.1 # GPU 가속을 위해 필수 (서버 환경)
  - pip:
      - mlflow==3.8.1
      - gitpython
      - numpy
      - pandas
      - tqdm
      - cloudpickle
name: mlflow-mnist-env