channels:
- conda-forge
dependencies:
- python=3.10.19
- pip<=25.3
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - numpy==2.2.6
  - pandas==2.3.3
  - torch==2.9.1
  - tqdm==4.67.1
name: mlflow-mnist-env