channels:
- pytorch  # 추가
- conda-forge
dependencies:
- python=3.10.19
- pip
- pytorch  # 추가
- torchvision # 추가 (MNIST 실습에 필요)
- pip:
  - mlflow==3.8.1  # 서버 버전과 맞추는 것이 좋습니다
  - cloudpickle
  - numpy
  - pandas
  - torch  # 버전 고정을 풀거나 최신 안정 버전으로 설정
  - tqdm
name: mlflow-mnist-env